# Anchorpoint Markup Language
# Predefined Variables: e.g. ${path}
# Environment Variables: e.g. ${MY_VARIABLE}
# Full documentation: https://docs.anchorpoint.app/docs/actions/create-actions

version: 1.0
action:
  name: Example / Create Set of Tasks

  version: 1
  id: ap::examples::setoftasks
  category: utility/code/examples/tasks
  type: python
  enable: false
  author: Anchorpoint Software GmbH
  description: Example action to demonstrate how to create tasks using the "New Task" button
  icon:
    path: :/icons/action.svg

  script: create_task_set.py

  register:
    new_task:
      enable: true