# Anchorpoint Markup Language
# Predefined Variables: e.g. ${path}
# Environment Variables: e.g. ${MY_VARIABLE}
# Full documentation: https://docs.anchorpoint.app/Actions/Reference

version: 1.0
action:
  name: New Project from Template

  version: 1
  id: ap::template::newproject
  category: template
  type: python
  enable: false
  author: Anchorpoint Software GmbH
  description: Creates a new project folder based on a set of templates
  icon:
    path: :/icons/project.svg

  inputs:
    template_dir: project_templates
    create_project: true

  script: templates.py

  dependencies:
    - project_templates

  register:
    folder:
      enable: true