# Anchorpoint Markup Language
# Predefined Variables: e.g. ${path}
# Environment Variables: e.g. ${MY_VARIABLE}
# Full documentation: https://docs.anchorpoint.app/Actions/Reference

version: 1.0
action:
  name: Settings Example

  version: 1
  id: ap::examples::settings
  category: utility/code/examples/settings
  type: python
  enable: false
  author: Anchorpoint Software GmbH
  description: An example action that demonstrates how to read and write action settings
  icon:
    path: :/icons/settings.svg

  script: settings_example.py

  register:
    folder:
      enable: true