# Anchorpoint Markup Language
# Predefined Variables: e.g. ${path}
# Environment Variables: e.g. ${MY_VARIABLE}
# Full documentation: https://docs.anchorpoint.app/docs/actions/create-actions

version: 1.0
action:
  name: Add GitIgnore Config

  version: 1
  id: git::ignoretemplate
  category: git
  type: python
  author: Anchorpoint Software GmbH
  description: Add a git ignore file from a set of templates
  icon:
    path: :/icons/versioncontrol.svg

  script: add_ignore_config.py

  register:
    folder:
      enable: add_ignore_config.py